### ISSUE TITLE
How to change db name, root password

### ISSUE THREAD

**Issue by sfu2** [oscarfonts/docker-h2#11]
I have used Mysql in docker and it provides -e options to create a container with specified  db name, user name and password. Is there an option with your docker image ?

**Comment by lcofre** [comment]
You are limited to the options that can be passed to the H2 server. They can be added to the environment variable `H2_OPTIONS`. Try with the value `-ifNotExists` to create the database when connecting.

```
docker run -d -p 1521:1521 -p 81:81 -e H2_OPTIONS='-ifNotExists' --name=MyH2Instance oscarfonts/h2
```

Then your database URL could be `jdbc:h2:tcp:localhost:1521/testdb` to create a database named testdb

**Comment by sfu2** [comment]
Thanks.
