### ISSUE TITLE
I got an error Database /opt/h2-data/test not found

### ISSUE THREAD

**Issue by gwagdalf** [oscarfonts/docker-h2#8]
I followed the instructions in the readme but I get an error.
can you help me?

error : Database "/opt/h2-data/test" not found, and IFEXISTS=true, so we cant auto-create it [90146-199] 90146/90146

![image](https://user-images.githubusercontent.com/34761230/66012591-c176e280-e502-11e9-89d5-d60e62a19d87.png)

I did like below
docker pull oscarfonts/h2
docker run -d -p 1521:1521 -p 81:81 -v /path/to/local/data_dir:/opt/h2-data --name=MyH2Instance oscarfonts/h2
docker logs -f MyH2Instance

http://localhost:81

**Comment by gwagdalf** [comment]
I found a solution " -ifNotExists "

https://stackoverflow.com/questions/55349373/database-not-found-and-ifexists-true-so-we-cant-auto-create-it

**Comment by CatarinaFranco94** [comment]
I solve the problem, on windows, by adding:
`-e H2_OPTIONS="-ifNotExists" `

In oscarfonts docker hub, it is `-e H2_OPTIONS='-ifNotExists' ` with single quotes but on windows, this causes  `Exception in thread "main" org.h2.jdbc. It has to be with "
